CREATE TABLE Users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    pwhash TEXT NOT NULL,
    image BLOB
);
CREATE TABLE Posts (
    id INTEGER PRIMARY KEY,
    content TEXT NOT NULL,
    time TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES Users ON DELETE CASCADE,
    class_id INTEGER NOT NULL REFERENCES Classes ON DELETE RESTRICT
);
CREATE TABLE Comments (
    id INTEGER PRIMARY KEY,
    content TEXT NOT NULL,
    time TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES Users ON DELETE CASCADE,
    post_id INTEGER NOT NULL REFERENCES Posts ON DELETE CASCADE
);
CREATE TABLE Classes (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);
CREATE INDEX idx_post_comments ON Comments (post_id);
